apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  namespace: jobautomation
  labels:
    app: jaeger
    component: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        component: tracing
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.47
        ports:
        - containerPort: 16686
          name: jaeger-ui
        - containerPort: 14268
          name: jaeger-collector
        - containerPort: 14250
          name: jaeger-grpc
        - containerPort: 6831
          protocol: UDP
          name: jaeger-agent-1
        - containerPort: 6832
          protocol: UDP
          name: jaeger-agent-2
        - containerPort: 5778
          name: jaeger-configs
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch.jobautomation.svc.cluster.local:9200"
        - name: ES_INDEX_PREFIX
          value: "jaeger"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: jobautomation
  labels:
    app: jaeger
    component: tracing
spec:
  selector:
    app: jaeger
  ports:
  - name: jaeger-ui
    port: 16686
    targetPort: 16686
  - name: jaeger-collector
    port: 14268
    targetPort: 14268
  - name: jaeger-grpc
    port: 14250
    targetPort: 14250
  - name: jaeger-agent-1
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jaeger-agent-2
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: jaeger-configs
    port: 5778
    targetPort: 5778
  - name: zipkin
    port: 9411
    targetPort: 9411
  type: ClusterIP