apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-automation-deployment
  namespace: jobautomation
  labels:
    app: job-automation
    component: automation
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: job-automation
  template:
    metadata:
      labels:
        app: job-automation
        component: automation
    spec:
      containers:
      - name: job-automation
        image: job-automation/automation:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http-port
        env:
        - name: CLICKHOUSE_HOST
          value: "clickhouse-service"
        - name: CLICKHOUSE_PORT
          value: "8123"
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              name: clickhouse-secret
              key: username
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-secret
              key: password
        - name: CLICKHOUSE_DB
          value: "job_automation"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FLASK_ENV
          value: "production"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: automation-logs
          mountPath: /app/logs
        - name: automation-data
          mountPath: /app/data
        - name: resumes
          mountPath: /app/resumes
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: automation-logs
        emptyDir: {}
      - name: automation-data
        emptyDir: {}
      - name: resumes
        persistentVolumeClaim:
          claimName: resumes-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: job-automation-service
  namespace: jobautomation
  labels:
    app: job-automation
    component: automation
spec:
  selector:
    app: job-automation
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resumes-pvc
  namespace: jobautomation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi