apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: jobautomation
data:
  custom.xml: |
    <clickhouse>
        <logger>
            <level>information</level>
            <log>/var/log/clickhouse-server/clickhouse-server.log</log>
            <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
            <size>1000M</size>
            <count>10</count>
        </logger>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <listen_host>0.0.0.0</listen_host>
        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
    </clickhouse>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-init-scripts
  namespace: jobautomation
data:
  01-create-database.sql: |
    CREATE DATABASE IF NOT EXISTS job_automation;
    USE job_automation;

    CREATE TABLE IF NOT EXISTS jobs (
        id String,
        title String,
        company String,
        location String,
        salary_min Nullable(Int32),
        salary_max Nullable(Int32),
        job_type String,
        employment_type String,
        description String,
        requirements String,
        url String,
        source String,
        posted_date DateTime,
        scraped_at DateTime DEFAULT now(),
        location_type String DEFAULT 'onsite',
        remote_friendly Boolean DEFAULT false,
        experience_level String DEFAULT 'mid',
        department String DEFAULT '',
        skills Array(String) DEFAULT [],
        benefits Array(String) DEFAULT [],
        company_size String DEFAULT '',
        industry String DEFAULT '',
        is_active Boolean DEFAULT true,
        application_deadline Nullable(DateTime),
        job_function String DEFAULT '',
        seniority_level String DEFAULT '',
        company_url String DEFAULT '',
        logo_url String DEFAULT '',
        application_count Nullable(Int32),
        view_count Nullable(Int32),
        geo_latitude Nullable(Float64),
        geo_longitude Nullable(Float64),
        created_at DateTime DEFAULT now(),
        updated_at DateTime DEFAULT now()
    ) ENGINE = MergeTree()
    ORDER BY (source, posted_date, id)
    PARTITION BY toYYYYMM(posted_date)
    TTL posted_date + INTERVAL 6 MONTH;

  02-create-user.sql: |
    CREATE USER IF NOT EXISTS automation_user IDENTIFIED BY 'secure_password_123';
    GRANT ALL PRIVILEGES ON job_automation.* TO automation_user;
    GRANT SHOW DATABASES ON *.* TO automation_user;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: jobautomation
data:
  app.conf: |
    [database]
    clickhouse_host = clickhouse-service
    clickhouse_port = 8123
    clickhouse_db = job_automation

    [redis]
    redis_host = redis-service
    redis_port = 6379

    [scraping]
    max_concurrent_scrapers = 10
    scrape_interval = 300
    user_agents = Mozilla/5.0 (compatible; JobBot/1.0)

    [automation]
    max_applications_per_hour = 50
    success_threshold = 0.7
    retry_attempts = 3