apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-web-deployment
  namespace: jobautomation
  labels:
    app: job-web
    component: web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: job-web
  template:
    metadata:
      labels:
        app: job-web
        component: web
    spec:
      containers:
      - name: job-web
        image: job-automation/web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http-port
        env:
        - name: FLASK_ENV
          value: "production"
        - name: CLICKHOUSE_HOST
          value: "clickhouse-service"
        - name: CLICKHOUSE_PORT
          value: "8123"
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              name: clickhouse-secret
              key: username
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-secret
              key: password
        - name: CLICKHOUSE_DB
          value: "job_automation"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: templates
          mountPath: /app/templates
        - name: static
          mountPath: /app/static
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: templates
        configMap:
          name: web-templates
      - name: static
        configMap:
          name: web-static
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: job-web-service
  namespace: jobautomation
  labels:
    app: job-web
    component: web
spec:
  selector:
    app: job-web
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP