apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-automation-app
  namespace: argocd
  labels:
    app: job-automation
    component: application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: job-automation-project
  source:
    repoURL: https://github.com/your-org/awesome-apply.git
    targetRevision: HEAD
    path: k8s/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: jobautomation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - PrunePropagationPolicy=foreground
    - Replace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-automation-monitoring
  namespace: argocd
  labels:
    app: job-automation-monitoring
    component: monitoring
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: job-automation-project
  source:
    repoURL: https://github.com/your-org/awesome-apply.git
    targetRevision: HEAD
    path: k8s/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: jobautomation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-automation-istio
  namespace: argocd
  labels:
    app: job-automation-istio
    component: service-mesh
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: job-automation-project
  source:
    repoURL: https://github.com/your-org/awesome-apply.git
    targetRevision: HEAD
    path: k8s/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: jobautomation
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m