apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: jobautomation
  labels:
    app: kibana
    component: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        component: logging
    spec:
      containers:
      - name: kibana
        image: kibana:8.9.0
        ports:
        - containerPort: 5601
          name: kibana
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch.jobautomation.svc.cluster.local:9200"
        - name: SERVER_NAME
          value: "kibana.jobautomation.svc.cluster.local"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
          value: "min-32-byte-long-strong-encryption-key"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: jobautomation
  labels:
    app: kibana
    component: logging
spec:
  selector:
    app: kibana
  ports:
  - name: kibana
    port: 5601
    targetPort: 5601
  type: ClusterIP